---
  version: "3.3"
  services:
    jupyter:
      build:
        context: "."
      image: "jupyter/r-notebook:latest"
      ports:
        - "8888:8888"
      volumes:
        - "./research:/home/jovyan/work"